// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scxzdhoaclusxlncjazm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjeHpkaG9hY2x1c3hsbmNqYXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMDY4MTgsImV4cCI6MjA4ODU4MjgxOH0.hmQgHpLk90LLNJAzSpKP-f-KM-g3xQY6X_3QbiqNT1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});